### PR TITLE
Fix travis ci

### PR DESCRIPTION
**Pull request by jwipeout**
Looks like ruby 2.4 added the sum method to Enumerable module, which causes the test to fail. https://ruby-doc.org/core-2.4.1/Enumerable.html#method-i-sum

### CODE REVIEW

**Comment by bbatsov** [comment]
Is Rubinius not supported by travis anymore?

As for the second commit - probably our `sum` should be changed to behave like the one in Ruby 2.4 for the sake of consistency.

**Comment by jwipeout** [comment]
- I read through travis ci and found we were missing Trusty to be able to use Rubinus :)
- Also updated the sum method to behave more like current one. Also added two more test cases that reflect the given examples.

**Comment by bbatsov** [comment]
The changes look good now. You should just squash all the commits into two - 1 fixing rbx and 1 fixing the tests and the definition of `sum`.

**Comment by jwipeout** [comment]
Squashed them!

**Pull request merged**
